- id: "1757380468247"
  alias: Update Travel Time Daytime
  description: ""
  triggers:
    - trigger: time_pattern
      hours: "*"
      minutes: /20
  conditions:
    - condition: time
      after: "08:00:00"
      before: "20:00:00"
  actions:
    - action: homeassistant.update_entity
      metadata: {}
      data:
        entity_id:
          - sensor.travel_aschau_kirchheim
          - sensor.travel_germering_kirchheim
          - sensor.travel_kirchheim_aschau
          - sensor.travel_kirchheim_germering
          - sensor.travel_kirchheim_work
          - sensor.travel_work_kirchheim
  mode: single
- id: "1757380880000"
  alias: Update Travel Time Nighttime
  description: ""
  triggers:
    - trigger: time_pattern
      hours: "*"
  conditions:
    - condition: time
      after: "20:00:00"
      before: "08:00:00"
  actions:
    - action: homeassistant.update_entity
      metadata: {}
      data:
        entity_id:
          - sensor.travel_aschau_kirchheim
          - sensor.travel_germering_kirchheim
          - sensor.travel_kirchheim_aschau
          - sensor.travel_kirchheim_germering
          - sensor.travel_kirchheim_work
          - sensor.travel_work_kirchheim
  mode: single
