homeassistant:
  name: Home
  latitude: !secret kirchheim_latitude
  longitude: !secret kirchheim_longitude
  elevation: !secret kirchheim_elevation
  unit_system: metric
  time_zone: Europe/Berlin

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  purge_keep_days: 30
  #exclude: !include includes/exclude.yaml
  db_url: !secret postgres_connection_url

ltss:
  db_url: !secret postgres_connection_url
  chunk_time_interval: 2592000000000
  include:
    domains:
      - sensor

automation: !include automations.yaml
zone: !include zone.yaml
