homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include includes/customize.yaml

# Enables the frontend
frontend:
ios:

# Enables configuration UI
config:

http:
  server_host: 127.0.0.1
  base_url: !secret http_url
  api_password: !secret http_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# tts:
#   platform: google

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: localhost
  client_id: home-assistant

ifttt:
    key: !secret ifttt_api_key

# automation: !include includes/automations.yaml
camera: !include includes/camera.yaml
group: !include includes/groups.yaml
light: !include includes/light.yaml
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
# script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
zone: !include includes/zones.yaml
