homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include includes/customize.yaml

# Enables the frontend
frontend:
ios:

# Enables configuration UI
config:

# Webserver config
http:
  server_host: 127.0.0.1
  base_url: !secret http_url
  api_password: !secret http_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Disable some overly verbose logs
logger:
  default: info
  logs:
    homeassistant.components.device_tracker: warn
    homeassistant.components.camera: warn
    homeassistant.components.http: warn

# InfluxDB logging
influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_user
  password: !secret influxdb_password
  exclude:
    entities:
       - entity.id1
    domains:
       - automation
  tags:
    instance: piot
    source: hass

# MQTT integration
mqtt:
  broker: localhost
  client_id: home-assistant

# IFTTT integration
ifttt:
  key: !secret ifttt_api_key

# Track the sun
sun:

automation: !include_dir_merge_list includes/automation
camera: !include includes/camera.yaml
group: !include includes/group.yaml
light: !include includes/light.yaml
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
sensor: !include_dir_merge_list includes/sensor
shell_command: !include includes/shell_command.yaml
zone: !include includes/zone.yaml

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Text to speech
# tts:
#   platform: google
