- platform: mqtt
  state_topic: "home/env/temp"
  name: "Temperature"
  unit_of_measurement: "°C"
  entity_namespace: aq
- platform: mqtt
  state_topic: "home/env/humi"
  name: "Humidity"
  unit_of_measurement: "%"
  entity_namespace: aq
- platform: mqtt
  state_topic: "home/env/pres"
  name: "Pressure"
  unit_of_measurement: "Pa"
  entity_namespace: aq
- platform: mqtt
  state_topic: "home/env/gasr"
  name: "CO2"
  unit_of_measurement: "CO2"
  entity_namespace: aq
