- platform: mqtt
  state_topic: "sensor/air-quality"
  name: "Temperature"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  state_topic: "sensor/air-quality"
  name: "Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  state_topic: "sensor/air-quality"
  name: "Pressure"
  unit_of_measurement: "Pa"
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  state_topic: "sensor/air-quality"
  name: "CO2"
  unit_of_measurement: "CO2"
  value_template: "{{ value_json.co2 }}"
- platform: mqtt
  state_topic: "sensor/air-quality"
  name: "TVOC"
  unit_of_measurement: "TVOC"
  value_template: "{{ value_json.tvoc }}"
