- platform: fritzbox_netmonitor
  host: !secret ip_fritz
- platform: speedtest
  minute:
    - 15
  monitored_conditions:
    - ping
    - download
    - upload
- platform: fastdotcom
  minute:
    - 30
