- platform: template
  sensors:
    tpicarus_amps:
      friendly_name: "Icarus current"
      icon_template: mdi:power-plug
      value_template: '{{ states.switch.tpicarus.attributes["current"] | replace(" A", "") | float }}'
      unit_of_measurement: 'A'
    tpicarus_volts:
      friendly_name: "Icarus voltage"
      icon_template: mdi:power-plug
      value_template: '{{ states.switch.tpicarus.attributes["voltage"] | replace(" V", "") | float }}'
      unit_of_measurement: 'V'
    tpicarus_watts:
      friendly_name: "Icarus power"
      icon_template: mdi:flash
      value_template: '{{ states.switch.tpicarus.attributes["current_consumption"] | replace(" W", "") | float }}'
      unit_of_measurement: 'W'
    tpicarus_kw_daily:
      friendly_name: "Icarus daily power"
      icon_template: mdi:flash
      value_template: '{{ states.switch.tpicarus.attributes["daily_consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
    tpicarus_kw_total:
      friendly_name: "Icarus total power"
      icon_template: mdi:flash
      value_template: '{{ states.switch.tpicarus.attributes["total_consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
