- platform: darksky
  name: DS
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - precip_probability
    - precip_intensity
    - temperature_min
    - temperature_max
    - humidity
- platform: moon
- platform: time_date
  display_options:
    - 'date_time'
#- platform: yr
#  monitored_conditions:
#    - temperature
#    - cloudiness
#    - precipitation
#    - windSpeed
